# SonarQube project configuration

# --- Required properties ---
# Must be unique in a given SonarQube instance
sonar.projectKey=vprofile-project
sonar.projectName=vprofile-project
# Version is set dynamically in the Jenkinsfile
# sonar.projectVersion=1.0

# --- Project settings ---
# Path is relative to the sonar-project.properties file.
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# --- Language settings ---
sonar.language=py

# --- Test and Coverage Reporting ---
# Paths to coverage and test reports.
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=xunit-reports.xml

# --- Exclusions ---
# Exclude virtual environment, build files, etc.
sonar.exclusions=**/__pycache__/**, .venv/**, venv/**, .git/**, .tox/**, build/**, dist/**, src/dist/**, src/*.egg-info/**
